### ISSUE TITLE
Where is the MainActivity called?

### ISSUE THREAD

**Issue by Fabi12345** [m-i-k-e-e/WifiPortalAutoLog#2]
I don't get it, I couldn't find any invoke of the MainActivity, how is that supposed to work?
It also says that a selection box appears where we can choose the autologin....it doesn't.

**Comment by Fabi12345** [comment]
Ah I see, its getting invoked by: 
`<action android:name="android.net.conn.CAPTIVE_PORTAL" />`
So, nevermind.
Might be some system settings what still block it.

**Comment by m-i-k-e-e** [comment]
It seems that it doesn't work on a Samsung device.The activity is launched by a broadcast.Le 22 juil. 2018 14:23, Fabi12345 <notifications@github.com> a écrit :I don't get it, I couldn't find any invoke of the MainActivity, how is that supposed to work?
It also says that a selection box appears where we can choose the autologin....it doesn't.

**Comment by Fabi12345** [comment]
Okay, so it seems it does not work on Xiaomi either.

**Comment by m-i-k-e-e** [comment]
I'll try to find one to do some testing.Le 22 juil. 2018 15:22, Fabi12345 <notifications@github.com> a écrit :Okay, so it seems it does not work on Xiaomi either.
